### ISSUE TITLE
Bump the `muddy` package version and publish

### ISSUE THREAD

**Issue by mrauhu** [orph3usLyre/muddy-waters#6]
Hello @orph3usLyre,

Can you please bump the package version and then publish it to the crates.io.

Thank you,
Sergey.

**Comment by orph3usLyre** [comment]
Hi @mrauhu,

I have a few additions planned this week and next, after which I'm going to make a new `v0.3.0` release :)

Generally, I want to add some basic CI (strict `clippy` mostly) as well as some basic testing just to validate when something breaks. I've also had a chat with a couple other devs regarding the expected output for users at build time, so I'll make a few minor changes and open PRs for them. I'd appreciate any input once they're up!

**Comment by orph3usLyre** [comment]
[Published!](https://crates.io/crates/muddy)
